### ISSUE TITLE
An item with the same key has already been added.

### ISSUE THREAD

**Issue by senikk** [Vodurden/Http-Multipart-Data-Parser#21] opened 2015-02-12 11:30 UTC
Is it possible to parse where the same key appears several times? I'm only getting `An item with the same key has already been added.` Its an email sent by mailgun to http where there are several `Content-Disposition: form-data; name="Received"`

**Comment by ueberboss** [comment] 2015-02-12 11:51
Hi senikk, I had the same issue and ended up just changing the way I name and handle fields.  The spec does not say it would be wrong to support this though - see "5.5 Ordered fields and duplicated field names" https://www.ietf.org/rfc/rfc2388.txt

**Comment by Vodurden** [comment] 2015-02-12 12:06
It's definitely possible to handle this. In particular if you use the new StreamingMultipartFormDataParser you can handle as many files and parameters as you want regardless of their name. However the simple MultipartParser can't support it without changing the interface through which you access Parameters.

**Comment by senikk** [comment] 2015-02-12 13:29
Yup. I have changed it myself to my needs and fixed the other issue with files not working anymore. Just a bit more code to get what I want like `parser.Parameters.Find(p => p.Name.ToLower() == "subject")` but not its not failing anymore :)

**Comment by Vodurden** [comment] 2015-02-13 23:15
Yeah. I'm not going to support this with the `MultipartFormDataParser` but it's simple to create another derivation from `StreamingMultipartFormDataParser` with the behaviour you want (or use `StreamingMultipartFormDataParser` directly). If there's a lot of demand I could create another derivation with the correct interface but I don't want to break any existing interfaces.

I'm going to close this now but if you've got any other questions or can see a reason why a new interface should be created let me know!

**Closed by Vodurden** 2015-02-13 23:15 UTC

**Comment by senikk** [comment] 2015-02-14 08:26
You could do a small fix the current interface checking if the key exists before adding it for paramteres so it doesn't fail reading multiparts with several equal keys. Som times you don't need the extra information given anyway.

**Comment by Vodurden** [comment] 2015-02-14 21:13
The issue in letting it silently fail is that it could lead to very confusing situations where you're losing data silently without knowing why. I'd rather to fail loudly if you're doing something that makes you lose data instead of letting it silently continue.

**Comment by senikk** [comment] 2015-02-15 00:02
If you use it to manage forwarded emails from mailgun you can´t use this library as it is because your http body contains several equal parameter keys like "Received" etc.

**Comment by Vodurden** [comment] 2015-02-15 04:46
For cases like that you can use the streaming multipart parser like so:

    var parser = new StreamingMultipartFormDataParser(stream);
    parser.ParameterHandler += parameter => 
    {
        // Do something with the parameter. We don't care if it has the same name.
    };
    parser.FileHandler += (name, fileName, type, disposition, buffer, bytes) =>
    {
        // Write the part of the file we've recieved to a file stream. (Or do something else)
        filestream.Write(buffer, 0, bytes);
    };

Alternatively if you look at the source code of MultipartFormDataParser (https://github.com/Vodurden/Http-Multipart-Data-Parser/blob/master/HttpMultipartParser/MultipartFormDataParser.cs) at around line 200 in the Constructor you can see it's fairly easy to define your own wrapper around the `StreamingMultipartFormDataParser` that can handle this situation. The issue is I don't want to create an entire new class just for handling parameters with multiple names in the simple way. If I were designing this library again from scratch this would certainly be something I would include but I don't want to break the existing interface for this when the `StreamingMultipartFormDataParser` can handle this case.

**Comment by senikk** [comment] 2015-02-15 07:21
I did it on friday myself so its in production allready ;)

**Comment by Vodurden** [comment] 2015-02-15 11:28
Awesome :) If you do ever think of another reason why I should change my stance on this make sure to let me know! Just because this particular issue is closed doesn't mean I don't want to be receptive to feedback about improving the library.

Thanks for taking the time to contribute!
