### ISSUE TITLE
TaskCanceledException throwed when StreamingMultipartFormDataParser.Run()

### ISSUE THREAD

**Issue by aaasoft** [Vodurden/Http-Multipart-Data-Parser#30] opened 2015-10-21 06:03 UTC
When upload some small file,everything is ok.
but when i test with a large file(vs2015.ent_chs.iso,3.88GB),TaskCanceledException will throw.the exception sometimes thowed when 2%,somtimes when 80%.it's random.

HttpMultipartParser dll version:2.0.1,from nuget
Test Browser:Chrome 44.0.2403.107 m

the exception detail is below:
-----------------------------------------------------
```
System.AggregateException: 发生一个或多个错误。 ---> System.Threading.Tasks.TaskCanceledException: 已取消一个任务。
   --- 内部异常堆栈跟踪的结尾 ---
   在 System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   在 System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   在 HttpMultipartParser.RebufferableBinaryReader.StreamData()
   在 HttpMultipartParser.RebufferableBinaryReader.Read(Byte[] buffer, Int32 index, Int32 count)
   在 HttpMultipartParser.StreamingMultipartFormDataParser.ParseFilePart(Dictionary`2 parameters, RebufferableBinaryReader reader)
   在 HttpMultipartParser.StreamingMultipartFormDataParser.ParseSection(RebufferableBinaryReader reader)
   在 HttpMultipartParser.StreamingMultipartFormDataParser.Parse(RebufferableBinaryReader reader)
   在 Quick.OwinMVC.Utils.MultipartFormDataUtils.HandleMultipartData(IOwinRequest req, ParameterDelegate parameterHandler, FileStreamDelegate fileHandler) 位置 E:\GitHub\Quick.OwinMVC\Source\Quick.OwinMVC\Utils\MultipartFormDataUtils.cs:行号 29
---> (内部异常 #0) System.Threading.Tasks.TaskCanceledException: 已取消一个任务。<---
```

**Comment by Vodurden** [comment] 2015-10-21 09:16
Hi aaasoft. I'm not entirely sure how to go about reproducing this. Typically a TaskCaneledException in a web context tends to occur when things time out. It's possible it's taking the reader too long to process the request which may be causing the timeout.

Given that there's no asynchronous code inside the multipart parser I'm not sure if it's an issue with the parser or a wider systems issue.

Any additional information would be appreciated.

**Comment by aaasoft** [comment] 2015-10-21 09:30
Hi Vodurden:

I use StreamingMultipartFormDataParser with Nowin(https://github.com/Bobris/Nowin) in my MVC project(https://github.com/aaasoft/Quick.OwinMVC),and i use a 500-error-handler middleware which has asynchronous code like ‘Next.Invoke(context).Wait();’.

I think this exception can't caused by timeout,because I test the same file,sometimes exception appear when 2%,sotimes exception appear when 80%,sometimes it's OK and no exception.

**Comment by Vodurden** [comment] 2015-10-21 09:33
The main thing I'm having trouble with is that we don't spawn any tasks in the MultipartParser codebase so I'm not sure how I would reproduce this issue in the library itself. It's possible that it's a large-file issue in which case I could try some stress testing on the library but I don't know if that would cause a `TaskCanceledException`

**Comment by aaasoft** [comment] 2015-10-21 09:38
After read your comment,maybe this Exception was casused by Nowin.I will make more test with Nowin.
Thanks for your reply.

**Comment by Vodurden** [comment] 2015-10-21 09:41
I'm glad I could help! 

I'm going to close the issue for now but If it turns out the issue is in this library please don't hesitate to let me know and we'll see how we can tackle it!

**Closed by Vodurden** 2015-10-21 09:41 UTC
